database:
      driverClass: org.h2.Driver
      user: sa
      password:
      url: jdbc:h2:~/dropwizard;MODE=MySQL;DATABASE_TO_UPPER=FALSE;INIT=RUNSCRIPT FROM 'classpath:/create-db.sql'
      properties:
         charSet: UTF-8
         validationQuery: "/* MyService Health Check */ SELECT 1"
